image: gitlab/dind
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: w0l1d
  APP_NAME: shop_imedia24_walid
  REPO: shop_imedia24_walid

stages:
  - build
  - test
  - docker

gradle-build:
  image: java:8-jdk
  stage: build
  only:
    - master
  script: "./gradlew build"
  artifacts:
    paths:
      - build/libs/*.jar

docker-build:
  stage: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/w0l1d/shop_imedia24_walid .
    - docker push registry.gitlab.com/w0l1d/shop_imedia24_walid